Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM1': WindowsError(1450, 'Insufficient system resources exist to complete the requested service.')

Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM1': WindowsError(1450, 'Insufficient system resources exist to complete the requested service.')

Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM1': WindowsError(1450, 'Insufficient system resources exist to complete the requested service.')

Exception in thread Thread-11:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM4': WindowsError(2, 'The system cannot find the file specified.')

Exception in thread Thread-12:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM4': WindowsError(2, 'The system cannot find the file specified.')

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM4': WindowsError(5, 'Access is denied.')

Exception in thread Thread-6:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM4': WindowsError(5, 'Access is denied.')

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM4': WindowsError(2, 'The system cannot find the file specified.')

Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM4': WindowsError(2, 'The system cannot find the file specified.')

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, 'Access is denied.')

Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, 'Access is denied.')

Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, 'Access is denied.')

Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, 'Access is denied.')

Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, 'Access is denied.')

Exception in thread Thread-6:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, 'Access is denied.')

Exception in thread Thread-7:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, 'Access is denied.')

Exception in thread Thread-8:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, 'Access is denied.')

Exception in thread Thread-9:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, 'Access is denied.')

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM1': WindowsError(1450, 'Insufficient system resources exist to complete the requested service.')

Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, 'Access is denied.')

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM4': WindowsError(5, 'Access is denied.')

